/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package formularios;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.beans.PropertyVetoException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author DEOCCIDENTE
 */
public class MainAdministrador extends javax.swing.JFrame {

    /**
     * Creates new form MainPuntoVentaGuadalupe
     */
    public MainAdministrador() {
        initComponents();
        
    }
    
    public int estado;
    public void acomodar(){
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        cutMenuItem = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        contentMenuItem = new javax.swing.JMenuItem();
        aboutMenuItem = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();

        desktopPane.setLayout(null);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Administrador");
        setBackground(new java.awt.Color(0, 0, 0));
        setIconImages(null);
        setLocationByPlatform(true);

        fileMenu.setMnemonic('f');
        fileMenu.setText("Login");
        fileMenu.setFont(new java.awt.Font("Baskerville Old Face", 1, 18)); // NOI18N
        fileMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileMenuActionPerformed(evt);
            }
        });

        jMenuItem1.setFont(new java.awt.Font("Baskerville Old Face", 0, 18)); // NOI18N
        jMenuItem1.setText("Cerrar Sesion...");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        fileMenu.add(jMenuItem1);

        menuBar.add(fileMenu);

        editMenu.setMnemonic('e');
        editMenu.setText("Inventario");
        editMenu.setFont(new java.awt.Font("Baskerville Old Face", 1, 18)); // NOI18N

        cutMenuItem.setFont(new java.awt.Font("Baskerville Old Face", 0, 18)); // NOI18N
        cutMenuItem.setMnemonic('t');
        cutMenuItem.setText("Nuevo Producto");
        cutMenuItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cutMenuItemMouseClicked(evt);
            }
        });
        cutMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cutMenuItemActionPerformed(evt);
            }
        });
        editMenu.add(cutMenuItem);

        jMenuItem6.setFont(new java.awt.Font("Baskerville Old Face", 0, 18)); // NOI18N
        jMenuItem6.setText("Editar Producto");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenuItem6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jMenuItem6KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jMenuItem6KeyReleased(evt);
            }
        });
        editMenu.add(jMenuItem6);

        jMenuItem2.setFont(new java.awt.Font("Baskerville Old Face", 0, 18)); // NOI18N
        jMenuItem2.setText("Ver Inventario");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        editMenu.add(jMenuItem2);

        menuBar.add(editMenu);

        helpMenu.setMnemonic('h');
        helpMenu.setText("Clientes");
        helpMenu.setFont(new java.awt.Font("Baskerville Old Face", 1, 18)); // NOI18N

        contentMenuItem.setFont(new java.awt.Font("Baskerville Old Face", 0, 18)); // NOI18N
        contentMenuItem.setMnemonic('c');
        contentMenuItem.setText("Nuevo Cliente");
        contentMenuItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                contentMenuItemMouseClicked(evt);
            }
        });
        contentMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contentMenuItemActionPerformed(evt);
            }
        });
        helpMenu.add(contentMenuItem);

        aboutMenuItem.setFont(new java.awt.Font("Baskerville Old Face", 0, 18)); // NOI18N
        aboutMenuItem.setMnemonic('a');
        aboutMenuItem.setText("Editar Cliente");
        aboutMenuItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                aboutMenuItemMouseClicked(evt);
            }
        });
        aboutMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutMenuItemActionPerformed(evt);
            }
        });
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        jMenu1.setText("Ventas");
        jMenu1.setFont(new java.awt.Font("Baskerville Old Face", 1, 18)); // NOI18N

        jMenuItem4.setFont(new java.awt.Font("Baskerville Old Face", 0, 18)); // NOI18N
        jMenuItem4.setText("Ver total De Ventas...");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuItem7.setFont(new java.awt.Font("Baskerville Old Face", 0, 18)); // NOI18N
        jMenuItem7.setText("Realizar Una Venta...");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem7);

        menuBar.add(jMenu1);

        jMenu3.setText("Usuarios");
        jMenu3.setFont(new java.awt.Font("Baskerville Old Face", 1, 18)); // NOI18N

        jMenuItem8.setFont(new java.awt.Font("Baskerville Old Face", 0, 18)); // NOI18N
        jMenuItem8.setText("Nuevo Usuario");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem8);

        jMenuItem3.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jMenuItem3.setText("Cambio de contraseña");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem3);

        menuBar.add(jMenu3);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1107, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 740, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fileMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileMenuActionPerformed
        
    }//GEN-LAST:event_fileMenuActionPerformed

    private void cutMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cutMenuItemActionPerformed
        IngresoProductos nuevoP = null;
        try {
            nuevoP = new IngresoProductos();
        } catch (SQLException ex) {
            Logger.getLogger(MainAdministrador.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MainAdministrador.class.getName()).log(Level.SEVERE, null, ex);
        }
      nuevoP.setResizable(true);
      nuevoP.pack();
      this.add(nuevoP);
     nuevoP.show();
    }//GEN-LAST:event_cutMenuItemActionPerformed

    private void cutMenuItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cutMenuItemMouseClicked
          IngresoProductos nuevoP = null;
        try {
            nuevoP = new IngresoProductos();
        } catch (SQLException ex) {
            Logger.getLogger(MainAdministrador.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MainAdministrador.class.getName()).log(Level.SEVERE, null, ex);
        }
      nuevoP.setResizable(true);
      nuevoP.pack();
      this.add(nuevoP);
     nuevoP.show();
        
       
        
    }//GEN-LAST:event_cutMenuItemMouseClicked

    private void contentMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contentMenuItemActionPerformed
        //Nuevo cliente
        ClienteNuevo nuevoC = null;
        nuevoC = new ClienteNuevo();
        nuevoC.setResizable(true);
        nuevoC.pack();
        this.add(nuevoC);
        nuevoC.show();
        
    }//GEN-LAST:event_contentMenuItemActionPerformed

    private void aboutMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutMenuItemActionPerformed
        //Editar Cliente
        ClienteEditar nuevoC = null;
        try {
            nuevoC = new ClienteEditar();
        } catch (SQLException ex) {
            Logger.getLogger(MainAdministrador.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MainAdministrador.class.getName()).log(Level.SEVERE, null, ex);
        }
        nuevoC.setResizable(true);
        nuevoC.pack();
        this.add(nuevoC);
        nuevoC.show();
    }//GEN-LAST:event_aboutMenuItemActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        try {
            // TODO add your handling code here:
            Login logg= new Login();
            logg.setVisible(true);
            this.dispose();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MainAdministrador.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        VerInventario nuevo= new VerInventario();
        nuevo.setResizable(true);
        nuevo.pack();
        this.add(nuevo);
        nuevo.show();
       
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        // TODO add your handling code here:
        CrearUsuariosInt nuevo= new CrearUsuariosInt();
                nuevo.setResizable(true);
                nuevo.pack();
                this.add(nuevo);
                nuevo.show();
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void contentMenuItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_contentMenuItemMouseClicked
        // TODO add your handling code here:
          ClienteNuevo nuevoC = null;
        nuevoC = new ClienteNuevo();
        nuevoC.setResizable(true);
        nuevoC.pack();
        this.add(nuevoC);
        nuevoC.show();
        
        
        
        
        
    }//GEN-LAST:event_contentMenuItemMouseClicked

    private void aboutMenuItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aboutMenuItemMouseClicked
          
        
        
        
    }//GEN-LAST:event_aboutMenuItemMouseClicked

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
        EditarProductos nuevo = null;
        try {
            nuevo = new EditarProductos();
        } catch (SQLException ex) {
            Logger.getLogger(MainAdministrador.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MainAdministrador.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        nuevo.setResizable(true);
        nuevo.pack();
        this.add(nuevo);
        nuevo.show();
       
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem6KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jMenuItem6KeyPressed
        // TODO add your handling code here:
        
       
    }//GEN-LAST:event_jMenuItem6KeyPressed

    private void jMenuItem6KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jMenuItem6KeyReleased
        // TODO add your handling code here:
        VerClientes verclientes= new VerClientes();
        try {
            verclientes.setSelected(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(MainAdministrador.class.getName()).log(Level.SEVERE, null, ex);
        }
        verclientes.pack();
        this.add(verclientes);
        verclientes.show();
    }//GEN-LAST:event_jMenuItem6KeyReleased

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        ReportesVentas nuevo= new ReportesVentas();
        nuevo.setResizable(true);
        nuevo.pack();
       
        this.add(nuevo);
        nuevo.show();
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
        VentaInt ventas = null;
        try {
            ventas = new VentaInt();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MainAdministrador.class.getName()).log(Level.SEVERE, null, ex);
        }
        ventas.setResizable(true);
        ventas.pack();
        this.add(ventas);
        ventas.show();
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        ChangePass cambio= null;
        cambio = new ChangePass();
        cambio.setResizable(true);
        cambio.pack();
        this.add(cambio);
        cambio.show();
        
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainAdministrador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JMenuItem contentMenuItem;
    private javax.swing.JMenuItem cutMenuItem;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JMenuBar menuBar;
    // End of variables declaration//GEN-END:variables

}
