/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package formularios;

import Reportes.ImprimirTicket;
import conexion.conexion;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;
import objetos.cliente;
import objetos.producto;
import transacciones.TransaccionVentas;
import transacciones.camposDB;

/**
 *
 * @author DEOCCIDENTE
 */
public class VentaInt extends javax.swing.JInternalFrame {

    /**
     * Creates new form VentaInt
     */
    public VentaInt() throws ClassNotFoundException {
        initComponents();
        numeroVenta();
    }
    DefaultTableModel m;
    int cont=0;
    float total; 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenu1 = new javax.swing.JMenu();
        jPopupMenu2 = new javax.swing.JPopupMenu();
        jMenu2 = new javax.swing.JMenu();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jPanel10 = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable5 = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jRadioButton6 = new javax.swing.JRadioButton();
        jRadioButton7 = new javax.swing.JRadioButton();
        jRadioButton8 = new javax.swing.JRadioButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jTextField3 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();

        jMenu1.setText("Enviar");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jPopupMenu1.add(jMenu1);

        jPopupMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPopupMenu2MouseClicked(evt);
            }
        });

        jMenu2.setText("Eliminar");
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        jPopupMenu2.add(jMenu2);

        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        jTabbedPane1.setFont(new java.awt.Font("Baskerville Old Face", 1, 14)); // NOI18N

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Tipo De Consulta"));
        jPanel4.setFont(new java.awt.Font("Baskerville Old Face", 1, 14)); // NOI18N

        jRadioButton3.setFont(new java.awt.Font("Baskerville Old Face", 1, 14)); // NOI18N
        jRadioButton3.setText("Por Nombre");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });

        jRadioButton4.setFont(new java.awt.Font("Baskerville Old Face", 1, 14)); // NOI18N
        jRadioButton4.setText("Por Apellido");
        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });

        jRadioButton5.setFont(new java.awt.Font("Baskerville Old Face", 1, 14)); // NOI18N
        jRadioButton5.setText("Por Codigo");
        jRadioButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(jRadioButton3)
                .addGap(37, 37, 37)
                .addComponent(jRadioButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jRadioButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton3)
                    .addComponent(jRadioButton4)
                    .addComponent(jRadioButton5))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Baskerville Old Face", 1, 14)); // NOI18N
        jLabel2.setText("Ingrese el nombre o texto de la consulta:");

        jTextField1.setFont(new java.awt.Font("Baskerville Old Face", 0, 14)); // NOI18N
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
        });

        jTable2.setFont(new java.awt.Font("Baskerville Old Face", 1, 14)); // NOI18N
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Codigo ", "Nombre ", "Apellido ", "Direccion", "Telefono"
            }
        ));
        jTable2.setComponentPopupMenu(jPopupMenu1);
        jScrollPane2.setViewportView(jTable2);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/buscar.png"))); // NOI18N
        jLabel6.setText("jLabel6");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 850, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(74, 74, 74)
                            .addComponent(jLabel2)
                            .addGap(33, 33, 33)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 544, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(66, 66, 66)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(301, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(121, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Consulta Informacion Cliente", jPanel2);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel1.setLayout(null);
        jPanel1.add(jLabel1);
        jLabel1.setBounds(979, 57, 0, 0);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Informacion Cliente:"));
        jPanel5.setFont(new java.awt.Font("Baskerville Old Face", 1, 14)); // NOI18N
        jPanel5.setLayout(null);

        jLabel12.setFont(new java.awt.Font("Baskerville Old Face", 1, 14)); // NOI18N
        jLabel12.setText("Nombre:");
        jPanel5.add(jLabel12);
        jLabel12.setBounds(30, 50, 59, 19);

        jLabel13.setFont(new java.awt.Font("Baskerville Old Face", 1, 14)); // NOI18N
        jLabel13.setText("Codigo Cliente:");
        jPanel5.add(jLabel13);
        jLabel13.setBounds(30, 20, 103, 25);

        jLabel14.setFont(new java.awt.Font("Baskerville Old Face", 1, 14)); // NOI18N
        jLabel14.setText("Apellido");
        jPanel5.add(jLabel14);
        jLabel14.setBounds(30, 80, 57, 19);

        jTextField2.setFont(new java.awt.Font("Baskerville Old Face", 0, 14)); // NOI18N
        jTextField2.setEnabled(false);
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jPanel5.add(jTextField2);
        jTextField2.setBounds(140, 20, 238, 25);

        jLabel15.setFont(new java.awt.Font("Baskerville Old Face", 0, 14)); // NOI18N
        jPanel5.add(jLabel15);
        jLabel15.setBounds(140, 50, 240, 20);

        jLabel16.setFont(new java.awt.Font("Baskerville Old Face", 0, 14)); // NOI18N
        jPanel5.add(jLabel16);
        jLabel16.setBounds(140, 80, 240, 20);

        jLabel17.setFont(new java.awt.Font("Baskerville Old Face", 1, 14)); // NOI18N
        jLabel17.setText("Telefono:");
        jPanel5.add(jLabel17);
        jLabel17.setBounds(510, 30, 66, 19);
        jPanel5.add(jLabel18);
        jLabel18.setBounds(435, 106, 0, 0);

        jLabel19.setFont(new java.awt.Font("Baskerville Old Face", 1, 14)); // NOI18N
        jLabel19.setText("Direccion:");
        jPanel5.add(jLabel19);
        jLabel19.setBounds(510, 80, 71, 19);

        jLabel20.setFont(new java.awt.Font("Baskerville Old Face", 0, 14)); // NOI18N
        jPanel5.add(jLabel20);
        jLabel20.setBounds(610, 40, 160, 25);

        jLabel21.setFont(new java.awt.Font("Baskerville Old Face", 0, 14)); // NOI18N
        jPanel5.add(jLabel21);
        jLabel21.setBounds(610, 90, 229, 25);

        jButton2.setFont(new java.awt.Font("Baskerville Old Face", 1, 14)); // NOI18N
        jButton2.setText("Aceptar");
        jButton2.setEnabled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton2);
        jButton2.setBounds(410, 20, 90, 27);

        jPanel1.add(jPanel5);
        jPanel5.setBounds(20, 20, 850, 142);

        jTable1.setFont(new java.awt.Font("Baskerville Old Face", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"", "", "", "", ""},
                {"", "", "", "", null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Codigo Producto", "Nombre Producto", "Precio Producto", "Cantidad", "Subtotal"
            }
        ));
        jTable1.setComponentPopupMenu(jPopupMenu2);
        jTable1.setEnabled(false);
        jTable1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTable1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTable1FocusLost(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(24, 268, 467, 186);

        jLabel22.setFont(new java.awt.Font("Baskerville Old Face", 1, 24)); // NOI18N
        jLabel22.setText("Total:");
        jPanel1.add(jLabel22);
        jLabel22.setBounds(30, 220, 65, 32);

        jLabel23.setFont(new java.awt.Font("Baskerville Old Face", 1, 14)); // NOI18N
        jLabel23.setText("0.00");
        jPanel1.add(jLabel23);
        jLabel23.setBounds(150, 230, 50, 19);

        jLabel24.setFont(new java.awt.Font("Baskerville Old Face", 1, 14)); // NOI18N
        jLabel24.setText("Q");
        jPanel1.add(jLabel24);
        jLabel24.setBounds(100, 230, 30, 19);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jRadioButton1.setFont(new java.awt.Font("Baskerville Old Face", 1, 12)); // NOI18N
        jRadioButton1.setText("NIT");
        jRadioButton1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRadioButton1ItemStateChanged(evt);
            }
        });
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        jRadioButton2.setFont(new java.awt.Font("Baskerville Old Face", 1, 12)); // NOI18N
        jRadioButton2.setText("C/F");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jRadioButton2)
                    .addComponent(jRadioButton1))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jRadioButton1)
                .addGap(18, 18, 18)
                .addComponent(jRadioButton2)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3);
        jPanel3.setBounds(900, 30, 110, 130);

        jLabel4.setFont(new java.awt.Font("Baskerville Old Face", 1, 14)); // NOI18N
        jLabel4.setText("Ingrese el nombre del Producto a buscar");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(590, 190, 287, 20);

        jTextField4.setFont(new java.awt.Font("Baskerville Old Face", 0, 14)); // NOI18N
        jTextField4.setEnabled(false);
        jTextField4.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                jTextField4InputMethodTextChanged(evt);
            }
        });
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        jTextField4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField4KeyReleased(evt);
            }
        });
        jPanel1.add(jTextField4);
        jTextField4.setBounds(590, 220, 480, 25);

        jScrollPane4.setFont(new java.awt.Font("Baskerville Old Face", 0, 14)); // NOI18N

        jTable4.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Cod. Producto", "Nombre ", "Descripcion", "Marca", "Existencias"
            }
        ));
        jTable4.setEnabled(false);
        jScrollPane4.setViewportView(jTable4);

        jPanel1.add(jScrollPane4);
        jScrollPane4.setBounds(588, 264, 614, 190);

        jButton1.setFont(new java.awt.Font("Baskerville Old Face", 1, 14)); // NOI18N
        jButton1.setText("<<");
        jButton1.setEnabled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(509, 338, 55, 65);

        jButton3.setFont(new java.awt.Font("Baskerville Old Face", 1, 18)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/ok.png"))); // NOI18N
        jButton3.setText("Realizar Venta");
        jButton3.setEnabled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(939, 470, 220, 60);

        jLabel25.setFont(new java.awt.Font("Baskerville Old Face", 1, 24)); // NOI18N
        jLabel25.setText("Cambio:");
        jPanel1.add(jLabel25);
        jLabel25.setBounds(290, 220, 95, 32);

        jLabel26.setFont(new java.awt.Font("Baskerville Old Face", 1, 14)); // NOI18N
        jLabel26.setText("Q");
        jPanel1.add(jLabel26);
        jLabel26.setBounds(390, 230, 30, 20);

        jLabel27.setFont(new java.awt.Font("Baskerville Old Face", 1, 14)); // NOI18N
        jLabel27.setText("0.00");
        jPanel1.add(jLabel27);
        jLabel27.setBounds(420, 230, 50, 19);

        jLabel28.setFont(new java.awt.Font("Baskerville Old Face", 1, 24)); // NOI18N
        jLabel28.setText("No. Venta:");
        jPanel1.add(jLabel28);
        jLabel28.setBounds(1060, 30, 118, 30);

        jLabel29.setFont(new java.awt.Font("Baskerville Old Face", 1, 24)); // NOI18N
        jLabel29.setText("0");
        jPanel1.add(jLabel29);
        jLabel29.setBounds(1090, 80, 30, 30);

        jTabbedPane1.addTab("Venta", jPanel1);

        jPanel8.setLayout(null);

        jLabel5.setFont(new java.awt.Font("Baskerville Old Face", 1, 14)); // NOI18N
        jLabel5.setText("Ingrese El codigo De la Factura a Devolver:");
        jPanel8.add(jLabel5);
        jLabel5.setBounds(80, 30, 304, 19);

        jTextField5.setFont(new java.awt.Font("Baskerville Old Face", 0, 14)); // NOI18N
        jPanel8.add(jTextField5);
        jTextField5.setBounds(380, 30, 331, 30);

        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder("Informacion Cliente:"));
        jPanel10.setFont(new java.awt.Font("Baskerville Old Face", 1, 14)); // NOI18N

        jLabel30.setFont(new java.awt.Font("Baskerville Old Face", 1, 14)); // NOI18N
        jLabel30.setText("Nombre:");

        jLabel31.setFont(new java.awt.Font("Baskerville Old Face", 1, 14)); // NOI18N
        jLabel31.setText("Codigo Cliente:");

        jLabel32.setFont(new java.awt.Font("Baskerville Old Face", 1, 14)); // NOI18N
        jLabel32.setText("Apellido");

        jTextField6.setFont(new java.awt.Font("Baskerville Old Face", 0, 14)); // NOI18N
        jTextField6.setEnabled(false);
        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });

        jLabel33.setFont(new java.awt.Font("Baskerville Old Face", 0, 14)); // NOI18N

        jLabel34.setFont(new java.awt.Font("Baskerville Old Face", 0, 14)); // NOI18N

        jLabel35.setFont(new java.awt.Font("Baskerville Old Face", 1, 14)); // NOI18N
        jLabel35.setText("Telefono:");

        jLabel37.setFont(new java.awt.Font("Baskerville Old Face", 1, 14)); // NOI18N
        jLabel37.setText("Direccion:");

        jLabel38.setFont(new java.awt.Font("Baskerville Old Face", 0, 14)); // NOI18N

        jLabel39.setFont(new java.awt.Font("Baskerville Old Face", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel32)
                        .addComponent(jLabel30)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField6, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
                    .addComponent(jLabel33, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel34, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(33, 33, 33)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabel35)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel38, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel10Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel36))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabel37)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel39, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel38, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField6)
                    .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel35)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel39, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel30)
                    .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel37))
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel32))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                        .addComponent(jLabel36)
                        .addGap(50, 50, 50))))
        );

        jPanel8.add(jPanel10);
        jPanel10.setBounds(80, 70, 775, 144);

        jTable5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Nombre Produc.", "Precio", "Cantidad", "Subtotal"
            }
        ));
        jScrollPane5.setViewportView(jTable5);

        jPanel8.add(jScrollPane5);
        jScrollPane5.setBounds(80, 220, 767, 350);

        jButton4.setFont(new java.awt.Font("Baskerville Old Face", 1, 14)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/ok.png"))); // NOI18N
        jButton4.setText("Confirmar Devolución");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton4);
        jButton4.setBounds(860, 210, 230, 60);

        jButton5.setFont(new java.awt.Font("Baskerville Old Face", 1, 14)); // NOI18N
        jButton5.setText("Aceptar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton5);
        jButton5.setBounds(760, 30, 100, 27);

        jTabbedPane1.addTab("Devoluciones", jPanel8);

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Tipo De Consulta"));
        jPanel7.setFont(new java.awt.Font("Baskerville Old Face", 1, 14)); // NOI18N

        jRadioButton6.setFont(new java.awt.Font("Baskerville Old Face", 1, 14)); // NOI18N
        jRadioButton6.setText("Por Nombre");
        jRadioButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton6ActionPerformed(evt);
            }
        });

        jRadioButton7.setFont(new java.awt.Font("Baskerville Old Face", 1, 14)); // NOI18N
        jRadioButton7.setText("Por Descripcion");
        jRadioButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton7ActionPerformed(evt);
            }
        });

        jRadioButton8.setFont(new java.awt.Font("Baskerville Old Face", 1, 14)); // NOI18N
        jRadioButton8.setText("Por Codigo");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jRadioButton6)
                .addGap(18, 18, 18)
                .addComponent(jRadioButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jRadioButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton6)
                    .addComponent(jRadioButton7)
                    .addComponent(jRadioButton8))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        jTable3.setFont(new java.awt.Font("Baskerville Old Face", 1, 14)); // NOI18N
        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Nombre", "Precio U.", "Precio M.", "Existencias", "Descripcion"
            }
        ));
        jScrollPane3.setViewportView(jTable3);

        jTextField3.setFont(new java.awt.Font("Baskerville Old Face", 0, 14)); // NOI18N
        jTextField3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField3KeyReleased(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Baskerville Old Face", 1, 14)); // NOI18N
        jLabel3.setText("Ingrese Lo que Desea Buscar:");

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/buscar.png"))); // NOI18N
        jLabel7.setText("jLabel6");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 527, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 730, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(410, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(22, 22, 22)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Consulta Informacion Producto", jPanel6);

        jButton6.setText("Salir");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 1222, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addGap(470, 470, 470)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 608, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton6ActionPerformed
        // TODO add your handling code here:
        jRadioButton7.setSelected(false);
        jRadioButton8.setSelected(false);
    }//GEN-LAST:event_jRadioButton6ActionPerformed

    private void jRadioButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton7ActionPerformed
        // TODO add your handling code here:
        jRadioButton6.setSelected(false);
        jRadioButton8.setSelected(false);
    }//GEN-LAST:event_jRadioButton7ActionPerformed

    private void jTextField3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField3KeyReleased
        // TODO add your handling code here:
        if(jRadioButton6.isSelected()){

            ConsultaProductosNombre();

        }else{
            if(jRadioButton7.isSelected()){

                ConsultaProductosDescripcion();
            }else{
                if(jRadioButton8.isSelected()){

                    ConsultaProductoCodigo();
                }
            }
        }
    }//GEN-LAST:event_jTextField3KeyReleased

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        // TODO add your handling code here:
        jRadioButton4.setSelected(false);
        jRadioButton5.setSelected(false);
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed
        // TODO add your handling code here:
        jRadioButton3.setSelected(false);
        jRadioButton5.setSelected(false);
    }//GEN-LAST:event_jRadioButton4ActionPerformed

    private void jRadioButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton5ActionPerformed
        // TODO add your handling code here:
        jRadioButton4.setSelected(false);
        jRadioButton3.setSelected(false);
    }//GEN-LAST:event_jRadioButton5ActionPerformed

    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased
        // TODO add your handling code here:
        if(jRadioButton3.isSelected()){
            ConsultarClienteNombre();
        }else{
            if(jRadioButton4.isSelected()){
                ConsultarClienteApellido();
            }else{
                if(jRadioButton5.isSelected()){
                    consultarClienteCodigo();
                }
            }
        }
    }//GEN-LAST:event_jTextField1KeyReleased

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

        TransaccionVentas consulta= new TransaccionVentas();
        cliente inf= new cliente();
        try {
            if(consulta.GetInfoCliente(jTextField2.getText()).GetNombreCliente()==null){
                JOptionPane.showMessageDialog(rootPane, "No se encuentra el cliente, Necesita crear un cliente para poder continuar");
            }else{
                HabilitarVenta();
                try {
                    inf=consulta.GetInfoCliente(jTextField2.getText());
                    jLabel15.setText(inf.GetNombreCliente());
                    jLabel16.setText(inf.GetApellidoCliente());
                    jLabel20.setText(inf.GetTelefonoCliente());
                    jLabel21.setText(inf.GetDireccionCliente());

                } catch (SQLException ex) {
                    Logger.getLogger(Venta.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(Venta.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(Venta.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Venta.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTable1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTable1FocusGained
        // TODO add your handling code here:
        float total;
    }//GEN-LAST:event_jTable1FocusGained

    private void jTable1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTable1FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1FocusLost

    private void jRadioButton1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioButton1ItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ItemStateChanged

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
        if(jRadioButton1.isSelected()){
            jTextField2.setEnabled(true);
            jButton2.setEnabled(true);
            jRadioButton2.setSelected(false);
        }else{
            jTextField2.setEnabled(false);
            jButton2.setEnabled(false);
        }
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
        if(jRadioButton2.isSelected()){
            jRadioButton1.setSelected(false);
            jTextField2.setEnabled(false);
            jButton2.setEnabled(false);
        }
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jTextField4InputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_jTextField4InputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4InputMethodTextChanged

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField4KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField4KeyReleased
        Connection cn=null;
        PreparedStatement pst;
        ResultSet rs;
        String comodin= jTextField4.getText() + "%";
        //String sql= "SELECT CodProducto, NombreProducto,PrecioUProducto,PrecioMayoristaProducto,tblMarca_idtblMarca(SELECT NombreMarca FROM tblMarca WHERE idtblMarca=tblMarca_idtblMarca) FROM tblProductos WHERE NombreProducto like'"+comodin+"'";
        // String sql= "(SELECT CodProducto,NombreProducto,DescripcionProducto, PrecioUproducto, PrecioMProducto,Existencias,(SELECT NombreMarca FROM tblMarca WHERE idtblMarca=tblMarca_idtblMarca) FROM tblProductos WHERE NombreProducto like'"+comodin+"')";
        String sql= "(SELECT tblProductos.CodProducto,tblProductos.NombreProducto,tblProductos.DescripcionProducto,tblProductos.PrecioUproducto,tblProductos.PrecioMProducto,tblProductos.Existencias, tblMarca.NombreMarca FROM tblProductos INNER JOIN tblMarca ON tblProductos.idtblMarca= tblMarca.idtblMarca WHERE NombreProducto like'"+comodin+"')";
        try {
            cn= conexion.getConexion();
            pst=cn.prepareCall(sql);
            rs=pst.executeQuery();
            jTable4.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jTextField4KeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String Precio,Cantidad = null;
        if(jTable4.getSelectedRow()!=-1){
            String codigo, Nombre, PrecioU,PrecioM,CantidadS,Existencias;
            float subtotal;

            Precio=JOptionPane.showInputDialog("Que tipo de Precio Desea Utilizar U/M");
            if(Precio!=null && (Precio.equals("U")||Precio.equals("u")||Precio.equals("M")||Precio.equals("m"))){
                Cantidad= JOptionPane.showInputDialog("Ingrese la cantidad de productos a vender");
                try {
                    if(Cantidad==null){
                        JOptionPane.showMessageDialog(rootPane, "Se ha cancelado la agregacion del producto");
                    }else{
                        Existencias= jTable4.getValueAt(jTable4.getSelectedRow(), 5).toString();
                        if(Integer.valueOf(Existencias)<=0 ||Integer.valueOf(Cantidad)>Integer.valueOf(Existencias)){
                            JOptionPane.showMessageDialog(rootPane, "No se puede realizar esta venta");
                        }else{

                            DefaultTableModel modelo= (DefaultTableModel) jTable1.getModel();
                            codigo=(String) jTable4.getValueAt(jTable4.getSelectedRow(), 0);
                            Nombre= jTable4.getValueAt(jTable4.getSelectedRow(), 1).toString();
                            PrecioU=jTable4.getValueAt(jTable4.getSelectedRow(), 3).toString();
                            PrecioM=jTable4.getValueAt(jTable4.getSelectedRow(), 4).toString();

                            m=(DefaultTableModel) jTable1.getModel();
                            m.setNumRows(cont);
                            if(Precio.equals("M")|| Precio.equals("m")){
                                subtotal= Float.parseFloat(PrecioM) * Float.parseFloat(Cantidad);
                                cont++;
                                String elementos[]= {codigo,Nombre,PrecioM,Cantidad,String.valueOf(subtotal)};
                                m.addRow(elementos);
                                total+=subtotal;
                            }else{
                                if(Precio.equals("U")||Precio.equals("u")){
                                    subtotal= Float.parseFloat(PrecioU) * Float.parseFloat(Cantidad);
                                    //  subtotal= Float.parseFloat(PrecioM) * Float.parseFloat(Cantidad);
                                    cont++;
                                    String elementos[]= {codigo,Nombre,PrecioU,Cantidad,String.valueOf((Math.round(subtotal*100.0)/100.0))};
                                    m.addRow(elementos);
                                    total+=subtotal;
                                }else{
                                    JOptionPane.showMessageDialog(rootPane, "Debio ingresar el tipo de precio a vender");
                                }
                            }
                            DecimalFormat df= new DecimalFormat("####.##");
                            //jLabel23.setText(String.valueOf(Math.round(total*Math.pow(10, 2))/Math.pow(10, 2)));
                              jLabel23.setText(String.valueOf(df.format(total)));

                        }
                    }
                } catch (NumberFormatException e) {
                    JOptionPane.showMessageDialog(rootPane, "el numero que ingreso no es un numero");
                }

            }else{
                JOptionPane.showMessageDialog(rootPane, "Se ha cancelado la agregacion del producto");
            }

        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String Pago;

        if(jTable1.getRowCount()==0 ||cont==0){
            JOptionPane.showMessageDialog(rootPane, "Nocesita agregar productos para poder efectuar la venta");
        }else{
            Pago= JOptionPane.showInputDialog("Ingrese El Pago");
       
            if(Float.parseFloat(Pago)==0 ||Float.parseFloat(Pago)<0||Float.parseFloat(Pago)<total){
                JOptionPane.showMessageDialog(rootPane, "Pago Invalido");
            }else{
                float cambio= Float.parseFloat(Pago)-total;
                TransaccionVentas ventas= new TransaccionVentas();
                DecimalFormat camb= new DecimalFormat("###.##");
                jLabel27.setText(String.valueOf(camb.format(cambio)));
                try {
                    ventas.InsertarFactura(jTextField2.getText(), total, ObtenerFechaSistema(), Float.parseFloat(Pago), cambio, true);
                    numeroFactura=ventas.ObtenerNumeroFactura();
                    ventas.InsertarDetalleFactura(jTable1, numeroFactura);
                    JOptionPane.showMessageDialog(rootPane, "Venta Realizada Exitosamente");
                    ActualizarInventario();
                    DecimalFormat pago1= new DecimalFormat("####.##");
                    ImprimirTicket(String.valueOf(Math.round(Float.parseFloat(Pago)*100.00)/100.00));
                    System.out.println(String.valueOf(Math.round(Float.parseFloat(Pago)*100.00)/100.00));
                    //GenerarReporte();
                    refresh();
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(rootPane, ex);
                    Logger.getLogger(Venta.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(Venta.class.getName()).log(Level.SEVERE, null, ex);
                }/* catch (JRException ex) {
                    Logger.getLogger(VentaInt.class.getName()).log(Level.SEVERE, null, ex);
                }*/
            }

        }

    }//GEN-LAST:event_jButton3ActionPerformed
   public String GetHoraSistema(){
        String fech;
            //en fecha obtenemos la fecha y hora del sistema
        Calendar fecha = new GregorianCalendar();
        //Obtenemos el valor del año, mes, día,
        //hora, minuto y segundo del sistema
        //usando el método get y el parámetro correspondiente
        int Hora = fecha.get(Calendar.HOUR_OF_DAY);
        int Minutos = fecha.get(Calendar.MINUTE);
        int segundos = fecha.get(Calendar.SECOND);
        fech= Hora +":"+Minutos+":"+segundos;
        
        return fech;
   }
    public void ImprimirTicket(String pago){
        FileWriter fw= null;
        try {
            ImprimirTicket nuevo= null;
            fw = new FileWriter("LPT1");
            PrintWriter pw= new PrintWriter(fw);
            nuevo= new ImprimirTicket();
            nuevo.PrintHeader(pw, jLabel29.getText(), ObtenerFechaSistema(),GetHoraSistema());
            nuevo.PrintInformacionCliente(pw, jTextField2.getText(),jLabel15.getText(), jLabel16.getText(), jLabel21.getText(), jLabel20.getText());
            nuevo.PrintHeaderVenta(pw);
            nuevo.PrintInformacionVenta(pw, jTable1);
            nuevo.PrintEndOfPage(pw,jLabel23.getText(),pago,jLabel27.getText());
        } catch (IOException ex) {
            Logger.getLogger(VentaInt.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            try {
                fw.close();
            } catch (IOException ex) {
                Logger.getLogger(VentaInt.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }
    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        try {
            // TODO add your handling code here:
            DevolucionDeProductos();
        } catch (SQLException ex) {
            Logger.getLogger(VentaInt.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(VentaInt.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        TransaccionVentas devolucion= new TransaccionVentas();
        devolucion.ActualizarEstadoFacturaFalse(Integer.parseInt(jTextField5.getText()));
        devolucion.devolucionSobreVentas(jTable5);
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        // TODO add your handling code here:
        jTextField2.setText(jTable2.getValueAt(jTable2.getSelectedRow(), 0).toString());
        JOptionPane.showMessageDialog(rootPane, "informacion Transferida para la venta");
    }//GEN-LAST:event_jMenu1MouseClicked

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
      
        

       
    }//GEN-LAST:event_formMouseClicked

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
        // TODO add your handling code here:
          if(jTable1.getSelectedRow()!=-1){
            DefaultTableModel modelo= (DefaultTableModel) jTable1.getModel();
        float precio=Float.parseFloat(modelo.getValueAt(jTable1.getSelectedRow(), 4).toString());
        modelo.removeRow(jTable1.getSelectedRow());
        
        total-=precio;
        cont--;
        jLabel23.setText(String.valueOf(total));
       
        System.out.println("Click");
        }
    }//GEN-LAST:event_jMenu2MouseClicked

    private void jPopupMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPopupMenu2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jPopupMenu2MouseClicked

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    public void GenerarReporte() throws JRException{
           
        try {
            com.mysql.jdbc.Connection cn= null;
            cn=(com.mysql.jdbc.Connection) conexion.getConexion();
            JasperReport jr =null;
            String archivo="C:\\puntovengaguadalupe\\src\\Reportes\\reportventa.jasper"; 
            Map parametro= new HashMap();
            TransaccionVentas NoFact= new TransaccionVentas();
            parametro.put("idFactura", NoFact.ObtenerNumeroFactura());
            jr= (JasperReport) JRLoader.loadObjectFromFile(archivo);
            JasperPrint jp= JasperFillManager.fillReport(jr, parametro, cn);
            JasperViewer jv= new JasperViewer(jp,false);
            jv.setVisible(true);
            jv.setDefaultCloseOperation(javax.swing.JFrame.DISPOSE_ON_CLOSE);
            jv.setTitle("Reporte");
        } catch (SQLException ex) {
            Logger.getLogger(Venta.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Venta.class.getName()).log(Level.SEVERE, null, ex);
        }
           
               
            
    }
    
    public void ActualizarInventario() {
       TransaccionVentas refres= new TransaccionVentas();
        for(int i=0;i< jTable1.getRowCount();i++){
            refres.actualizarInventario(Integer.parseInt((String) jTable1.getValueAt(i, 3)), (String) jTable1.getValueAt(i, 0));
        }
        
        
    }
     int numeroFactura;
    public void refresh(){
       total=0;
       numeroFactura=0;
       jLabel15.setText("");
       jLabel16.setText("");
       jLabel20.setText("");
       jLabel21.setText("");
       jTextField2.setText("");
       jRadioButton1.setSelected(false);
       jRadioButton2.setSelected(false);
       jLabel27.setText("0.00");
       jLabel23.setText("0.00");
       jTextField4.setText("");
      this.dispose();
       
    }
     public void HabilitarVenta(){
        jTextField4.setEnabled(true);
        jTable4.setEnabled(true);
        jButton1.setEnabled(true);
        jTable1.setEnabled(true);
        jButton3.setEnabled(true);
    }
    public void numeroVenta() throws ClassNotFoundException{
        TransaccionVentas obt= new TransaccionVentas();
        jLabel29.setText(String.valueOf(obt.ObtenerNumerVenta()+1));
    }
    public String ObtenerFechaSistema(){
        String fech;
            //en fecha obtenemos la fecha y hora del sistema
        Calendar fecha = new GregorianCalendar();
        //Obtenemos el valor del año, mes, día,
        //hora, minuto y segundo del sistema
        //usando el método get y el parámetro correspondiente
        int año = fecha.get(Calendar.YEAR);
        int mes = fecha.get(Calendar.MONTH)+1;
        int dia = fecha.get(Calendar.DAY_OF_MONTH);
        fech= año +"."+mes+"."+dia;
        
        return fech;
    }
    public void ConsultarClienteNombre(){
         Connection cn=null;
        PreparedStatement pst;
        ResultSet rs;
        String comodin= jTextField1.getText() + "%";
        //String sql= "SELECT CodProducto, NombreProducto,PrecioUProducto,PrecioMayoristaProducto,tblMarca_idtblMarca(SELECT NombreMarca FROM tblMarca WHERE idtblMarca=tblMarca_idtblMarca) FROM tblProductos WHERE NombreProducto like'"+comodin+"'";
        String sql= "(SELECT CodCliente,NombreCliente,ApellidoCliente, TelefonoCliente, DireccionCliente FROM tblClientes WHERE NombreCliente like '"+comodin+"')";
       
        try {
            cn= conexion.getConexion();
            pst=cn.prepareCall(sql);
            rs=pst.executeQuery();
            jTable2.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception e) {
        }
    }
    public void ConsultarClienteApellido(){
         Connection cn=null;
        PreparedStatement pst;
        ResultSet rs;
        String comodin= jTextField1.getText() + "%";
        //String sql= "SELECT CodProducto, NombreProducto,PrecioUProducto,PrecioMayoristaProducto,tblMarca_idtblMarca(SELECT NombreMarca FROM tblMarca WHERE idtblMarca=tblMarca_idtblMarca) FROM tblProductos WHERE NombreProducto like'"+comodin+"'";
        String sql= "(SELECT CodCliente,NombreCliente,ApellidoCliente, TelefonoCliente, DireccionCliente FROM tblClientes WHERE ApellidoCliente like '"+comodin+"')";
       
        try {
            cn= conexion.getConexion();
            pst=cn.prepareCall(sql);
            rs=pst.executeQuery();
            jTable2.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception e) {
        }
    }
    public void consultarClienteCodigo(){
         Connection cn=null;
        PreparedStatement pst;
        ResultSet rs;
        String comodin= jTextField1.getText() + "%";
        //String sql= "SELECT CodProducto, NombreProducto,PrecioUProducto,PrecioMayoristaProducto,tblMarca_idtblMarca(SELECT NombreMarca FROM tblMarca WHERE idtblMarca=tblMarca_idtblMarca) FROM tblProductos WHERE NombreProducto like'"+comodin+"'";
        String sql= "(SELECT CodCliente,NombreCliente,ApellidoCliente, TelefonoCliente, DireccionCliente FROM tblClientes WHERE CodCliente like '"+comodin+"')";
       
        try {
            cn= conexion.getConexion();
            pst=cn.prepareCall(sql);
            rs=pst.executeQuery();
            jTable2.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception e) {
        }
    }
    public void ConsultaProductosNombre(){
         Connection cn=null;
        PreparedStatement pst;
        ResultSet rs;
        String comodin= jTextField3.getText() + "%";
        //String sql= "SELECT CodProducto, NombreProducto,PrecioUProducto,PrecioMayoristaProducto,tblMarca_idtblMarca(SELECT NombreMarca FROM tblMarca WHERE idtblMarca=tblMarca_idtblMarca) FROM tblProductos WHERE NombreProducto like'"+comodin+"'";
        //String sql= "(SELECT CodProducto,NombreProducto,DescripcionProducto, PrecioUproducto, PrecioMProducto,Existencias,(SELECT NombreMarca FROM tblMarca WHERE idtblMarca=tblMarca_idtblMarca) FROM tblProductos WHERE NombreProducto like '"+comodin+"')";
       String sql= "(SELECT tblProductos.CodProducto,tblProductos.NombreProducto,tblProductos.DescripcionProducto,tblProductos.PrecioUproducto,tblProductos.PrecioMProducto, tblMarca.NombreMarca FROM tblProductos INNER JOIN tblMarca ON tblProductos.idtblMarca= tblMarca.idtblMarca WHERE NombreProducto like'"+comodin+"')";
        try {
            cn= conexion.getConexion();
            pst=cn.prepareCall(sql);
            rs=pst.executeQuery();
            jTable3.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception e) {
        }
    }
    public void ConsultaProductosDescripcion(){
         Connection cn=null;
        PreparedStatement pst;
        ResultSet rs;
        String comodin= jTextField3.getText() + "%";
        //String sql= "SELECT CodProducto, NombreProducto,PrecioUProducto,PrecioMayoristaProducto,tblMarca_idtblMarca(SELECT NombreMarca FROM tblMarca WHERE idtblMarca=tblMarca_idtblMarca) FROM tblProductos WHERE NombreProducto like'"+comodin+"'";
        // String sql= "(SELECT CodProducto,NombreProducto,DescripcionProducto, PrecioUproducto, PrecioMProducto,Existencias,(SELECT NombreMarca FROM tblMarca WHERE idtblMarca=tblMarca_idtblMarca) FROM tblProductos WHERE DescripcionProducto like'"+comodin+"')";
       String sql= "(SELECT tblProductos.CodProducto,tblProductos.NombreProducto,tblProductos.DescripcionProducto,tblProductos.PrecioUproducto,tblProductos.PrecioMProducto, tblMarca.NombreMarca FROM tblProductos INNER JOIN tblMarca ON tblProductos.idtblMarca= tblMarca.idtblMarca WHERE DescripcionProducto like'"+comodin+"')";
        try {
            cn= conexion.getConexion();
            pst=cn.prepareCall(sql);
            rs=pst.executeQuery();
            jTable3.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception e) {
        }
    }
    public void ConsultaProductoCodigo(){
         Connection cn=null;
        PreparedStatement pst;
        ResultSet rs;
        String comodin= jTextField3.getText() + "%";
        //String sql= "SELECT CodProducto, NombreProducto,PrecioUProducto,PrecioMayoristaProducto,tblMarca_idtblMarca(SELECT NombreMarca FROM tblMarca WHERE idtblMarca=tblMarca_idtblMarca) FROM tblProductos WHERE NombreProducto like'"+comodin+"'";
       // String sql= "(SELECT CodProducto,NombreProducto,DescripcionProducto, PrecioUproducto, PrecioMProducto,Existencias,(SELECT NombreMarca FROM tblMarca WHERE idtblMarca=tblMarca_idtblMarca) FROM tblProductos WHERE CodProducto like'"+comodin+"')";
        String sql= "(SELECT tblProductos.CodProducto,tblProductos.NombreProducto,tblProductos.DescripcionProducto,tblProductos.PrecioUproducto,tblProductos.PrecioMProducto, tblMarca.NombreMarca FROM tblProductos INNER JOIN tblMarca ON tblProductos.idtblMarca= tblMarca.idtblMarca WHERE CodProducto like'"+comodin+"')";
       
        try {
            cn= conexion.getConexion();
            pst=cn.prepareCall(sql);
            rs=pst.executeQuery();
            jTable3.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception e) {
        }
    }
    
    public void buscarNombreProducto(String CodProducto) throws SQLException, ClassNotFoundException{
        producto produ= new producto();
        Connection con= null;
        con=conexion.getConexion();
        Statement st = con.createStatement();
        ResultSet rs = st.executeQuery("SELECT CodProducto, NombreProducto, PrecioUProducto, PrecioMProducto,Existencias,DescripcionProducto FROM tblProductos WHERE CodProducto like '%" +CodProducto+'%');
        ResultSetMetaData rsMd = (ResultSetMetaData) rs.getMetaData();
         st = (Statement) con.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
        produ.SetNombreProducto(rs.getString("NombreProducto").intern());
        produ.SetPrecioUnitario(rs.getFloat("PrecioUProducto"));
        produ.SetPrecioMayorista(rs.getFloat("PrecioMProducto"));
        produ.SetExistencias(rs.getInt("Existencias"));
        produ.SetDescripcion(rs.getString("DescripcionProducto"));
        
        st.close();
        con.close();
    }
    
    public void DevolucionDeProductos() throws SQLException, ClassNotFoundException{
        cliente informacionCliente= new cliente();
        camposDB detalleFactura;
        
          Connection cn=null;
        PreparedStatement pst;
        Statement stm= null;
        ResultSet rs;
        String comodin= jTextField5.getText();
        cn= conexion.getConexion();
        String sql= "SELECT tblFactura.idFactura,tblFactura.FechaFactura,tblFactura.Total, tblProductos_has_tblFactura.tblProductos_CodProducto,tblProductos_has_tblFactura.Precio,tblProductos_has_tblFactura.Cantidad,tblProductos_has_tblFactura.Subtotal, tblProductos.NombreProducto,tblClientes.* FROM tblFactura INNER JOIN tblProductos_has_tblFactura ON tblProductos_has_tblFactura.tblFactura_idFactura= tblFactura.idFactura INNER JOIN tblProductos ON tblProductos_has_tblFactura.tblProductos_CodProducto=tblProductos.CodProducto INNER JOIN tblClientes ON  tblFactura.tblClientes_codCliente= tblClientes.codCliente WHERE idFactura='"+comodin+"' AND Activa=true";
            stm= cn.createStatement();
            rs=stm.executeQuery(sql);
            ArrayList <camposDB> detalleventa= new ArrayList<>();
            while(rs.next()){
                informacionCliente.setCodigoCliente(rs.getString("tblClientes.codCliente"));
                informacionCliente.SetNombreCliente(rs.getString("tblClientes.Nombrecliente"));
                informacionCliente.SetApellidoCliente(rs.getString("tblClientes.ApellidoCliente"));
                informacionCliente.SetDireccionCliente(rs.getString("tblClientes.DireccionCliente"));
                informacionCliente.SetTelefonoCliente(rs.getString("tblClientes.TelefonoCliente"));
                detalleFactura= new camposDB(rs.getString("tblProductos_has_tblFactura.tblProductos_CodProducto"), rs.getString("tblProductos.NombreProducto"), rs.getFloat("tblProductos_has_tblFactura.Precio"), rs.getInt("tblProductos_has_tblFactura.Cantidad"), rs.getFloat("tblProductos_has_tblFactura.Subtotal"));
                detalleventa.add(detalleFactura);
            }
            jTextField6.setText(informacionCliente.GetCodigoCliente());
            jLabel38.setText(informacionCliente.GetTelefonoCliente());
            jLabel33.setText(informacionCliente.GetNombreCliente());
            jLabel34.setText(informacionCliente.GetApellidoCliente());
            jLabel39.setText(informacionCliente.GetDireccionCliente());
            DefaultTableModel modelo = (DefaultTableModel) jTable5.getModel();
            modelo.addRow(new Object[detalleventa.size()]);
            modelo.setNumRows(detalleventa.size());
            for(int i=0; i<detalleventa.size();i++){
                jTable5.setValueAt(detalleventa.get(i).getCodigo(),i,0);
                jTable5.setValueAt(detalleventa.get(i).getNombre(), i, 1);
                jTable5.setValueAt(detalleventa.get(i).getPrecio(),i,2);
                jTable5.setValueAt(detalleventa.get(i).getCantidad(), i,3);
                jTable5.setValueAt(detalleventa.get(i).getSubtotal(), i, 4);
            }
            
            
            
            rs.close();
            cn.close();
            stm.close();
      
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu jPopupMenu2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JRadioButton jRadioButton8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    private javax.swing.JTable jTable5;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration//GEN-END:variables
}
