/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package formularios;
import transacciones.camposDB;
import conexion.conexion;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.HashMap;
import java.util.LinkedList;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.data.JRBeanCollectionDataSource;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.swing.JRViewer;
import net.sf.jasperreports.view.JasperViewer;
import objetos.*;
import transacciones.*;
/**
 *
 * @author DEOCCIDENTE
 */
public class Venta extends javax.swing.JFrame {

    /**
     * Creates new form Venta
     */
    public Venta() throws ClassNotFoundException {
        initComponents();
        numeroVenta();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jRadioButton6 = new javax.swing.JRadioButton();
        jRadioButton7 = new javax.swing.JRadioButton();
        jRadioButton8 = new javax.swing.JRadioButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jTextField3 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jTextField5 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Tipo De Consulta"));
        jPanel4.setFont(new java.awt.Font("Baskerville Old Face", 1, 14)); // NOI18N

        jRadioButton3.setFont(new java.awt.Font("Baskerville Old Face", 1, 14)); // NOI18N
        jRadioButton3.setText("Por Nombre");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });

        jRadioButton4.setFont(new java.awt.Font("Baskerville Old Face", 1, 14)); // NOI18N
        jRadioButton4.setText("Por Apellido");
        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });

        jRadioButton5.setFont(new java.awt.Font("Baskerville Old Face", 1, 14)); // NOI18N
        jRadioButton5.setText("Por Codigo");
        jRadioButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton5ActionPerformed(evt);
            }
        });

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/buscar.png"))); // NOI18N
        jLabel7.setText("jLabel6");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(jRadioButton3)
                .addGap(91, 91, 91)
                .addComponent(jRadioButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76)
                .addComponent(jRadioButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton3)
                    .addComponent(jRadioButton4)
                    .addComponent(jRadioButton5))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel2.setFont(new java.awt.Font("Baskerville Old Face", 1, 18)); // NOI18N
        jLabel2.setText("Ingrese el nombre o texto de la consulta:");

        jTextField1.setFont(new java.awt.Font("Baskerville Old Face", 0, 18)); // NOI18N
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
        });

        jTable2.setFont(new java.awt.Font("Baskerville Old Face", 1, 14)); // NOI18N
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Codigo ", "Nombre ", "Apellido ", "Direccion", "Telefono"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 544, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(338, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Consulta Informacion Cliente", jPanel2);

        jPanel6.setLayout(null);

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Tipo De Consulta"));
        jPanel7.setFont(new java.awt.Font("Baskerville Old Face", 1, 14)); // NOI18N

        jRadioButton6.setFont(new java.awt.Font("Baskerville Old Face", 1, 14)); // NOI18N
        jRadioButton6.setText("Por Nombre");
        jRadioButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton6ActionPerformed(evt);
            }
        });

        jRadioButton7.setFont(new java.awt.Font("Baskerville Old Face", 1, 14)); // NOI18N
        jRadioButton7.setText("Por Descripcion");
        jRadioButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton7ActionPerformed(evt);
            }
        });

        jRadioButton8.setFont(new java.awt.Font("Baskerville Old Face", 1, 14)); // NOI18N
        jRadioButton8.setText("Por Codigo");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(jRadioButton6)
                .addGap(139, 139, 139)
                .addComponent(jRadioButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 168, Short.MAX_VALUE)
                .addComponent(jRadioButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton6)
                    .addComponent(jRadioButton7)
                    .addComponent(jRadioButton8))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jPanel6.add(jPanel7);
        jPanel7.setBounds(47, 11, 840, 88);

        jScrollPane3.setFont(new java.awt.Font("Baskerville Old Face", 0, 14)); // NOI18N

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Nombre", "Precio U.", "Precio M.", "Existencias", "Descripcion"
            }
        ));
        jScrollPane3.setViewportView(jTable3);

        jPanel6.add(jScrollPane3);
        jScrollPane3.setBounds(50, 170, 850, 343);

        jTextField3.setFont(new java.awt.Font("Baskerville Old Face", 0, 14)); // NOI18N
        jTextField3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField3KeyReleased(evt);
            }
        });
        jPanel6.add(jTextField3);
        jTextField3.setBounds(270, 130, 630, 21);

        jLabel3.setFont(new java.awt.Font("Baskerville Old Face", 1, 14)); // NOI18N
        jLabel3.setText("Ingrese Lo que Desea Buscar:");
        jPanel6.add(jLabel3);
        jLabel3.setBounds(50, 130, 195, 15);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/buscar.png"))); // NOI18N
        jLabel9.setText("jLabel6");
        jPanel6.add(jLabel9);
        jLabel9.setBounds(930, 20, 69, 72);

        jTabbedPane1.addTab("Consulta Informacion Producto", jPanel6);

        jLabel5.setFont(new java.awt.Font("Baskerville Old Face", 1, 14)); // NOI18N
        jLabel5.setText("Ingrese El codigo De la Factura a Devolver:");

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder("Informacion Cliente"));
        jPanel9.setFont(new java.awt.Font("Baskerville Old Face", 1, 14)); // NOI18N

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 674, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 121, Short.MAX_VALUE)
        );

        jTextField5.setFont(new java.awt.Font("Baskerville Old Face", 0, 14)); // NOI18N

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/buscar.png"))); // NOI18N
        jLabel8.setText("jLabel6");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(69, 69, 69)
                        .addComponent(jLabel8)))
                .addContainerGap(365, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(233, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Devoluciones", jPanel8);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel1.setLayout(null);
        jPanel1.add(jLabel1);
        jLabel1.setBounds(1013, 57, 0, 0);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Informacion Cliente:"));
        jPanel5.setFont(new java.awt.Font("Baskerville Old Face", 1, 14)); // NOI18N

        jLabel12.setFont(new java.awt.Font("Baskerville Old Face", 1, 14)); // NOI18N
        jLabel12.setText("Nombre:");

        jLabel13.setFont(new java.awt.Font("Baskerville Old Face", 1, 14)); // NOI18N
        jLabel13.setText("Codigo Cliente:");

        jLabel14.setFont(new java.awt.Font("Baskerville Old Face", 1, 14)); // NOI18N
        jLabel14.setText("Apellido");

        jTextField2.setFont(new java.awt.Font("Baskerville Old Face", 0, 14)); // NOI18N
        jTextField2.setEnabled(false);
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Baskerville Old Face", 0, 14)); // NOI18N

        jLabel16.setFont(new java.awt.Font("Baskerville Old Face", 0, 14)); // NOI18N

        jLabel17.setFont(new java.awt.Font("Baskerville Old Face", 1, 14)); // NOI18N
        jLabel17.setText("Telefono:");

        jLabel19.setFont(new java.awt.Font("Baskerville Old Face", 1, 14)); // NOI18N
        jLabel19.setText("Direccion:");

        jButton2.setFont(new java.awt.Font("Baskerville Old Face", 1, 14)); // NOI18N
        jButton2.setText("Aceptar");
        jButton2.setEnabled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(4, 4, 4)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addGap(76, 76, 76)
                                .addComponent(jLabel19))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jButton2)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel17)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel21, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel17)
                        .addComponent(jButton2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14))
                        .addContainerGap(22, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel5Layout.createSequentialGroup()
                                    .addComponent(jLabel18)
                                    .addGap(14, 14, 14))
                                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(15, 15, 15))))
        );

        jPanel1.add(jPanel5);
        jPanel5.setBounds(33, 27, 818, 142);

        jScrollPane1.setFont(new java.awt.Font("Baskerville Old Face", 0, 14)); // NOI18N

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"", "", "", "", ""},
                {"", "", "", "", null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Codigo Producto", "Nombre Producto", "Precio Producto", "Cantidad", "Subtotal"
            }
        ));
        jTable1.setEnabled(false);
        jTable1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTable1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTable1FocusLost(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(30, 260, 467, 186);

        jLabel22.setFont(new java.awt.Font("Baskerville Old Face", 1, 24)); // NOI18N
        jLabel22.setText("Total:");
        jPanel1.add(jLabel22);
        jLabel22.setBounds(30, 220, 80, 24);

        jLabel23.setFont(new java.awt.Font("Baskerville Old Face", 1, 24)); // NOI18N
        jLabel23.setText("0.00");
        jPanel1.add(jLabel23);
        jLabel23.setBounds(150, 220, 60, 24);

        jLabel24.setFont(new java.awt.Font("Baskerville Old Face", 1, 24)); // NOI18N
        jLabel24.setText("Q");
        jPanel1.add(jLabel24);
        jLabel24.setBounds(110, 220, 30, 24);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jRadioButton1.setFont(new java.awt.Font("Baskerville Old Face", 1, 14)); // NOI18N
        jRadioButton1.setText("NIT");
        jRadioButton1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRadioButton1ItemStateChanged(evt);
            }
        });
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        jRadioButton2.setFont(new java.awt.Font("Baskerville Old Face", 1, 14)); // NOI18N
        jRadioButton2.setText("C/F");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton2)
                    .addComponent(jRadioButton1))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jRadioButton1)
                .addGap(18, 18, 18)
                .addComponent(jRadioButton2)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3);
        jPanel3.setBounds(860, 40, 140, 116);

        jLabel4.setFont(new java.awt.Font("Baskerville Old Face", 1, 18)); // NOI18N
        jLabel4.setText("Ingrese el nombre del Producto a buscar");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(580, 190, 324, 19);

        jTextField4.setFont(new java.awt.Font("Baskerville Old Face", 0, 18)); // NOI18N
        jTextField4.setEnabled(false);
        jTextField4.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                jTextField4InputMethodTextChanged(evt);
            }
        });
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        jTextField4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField4KeyReleased(evt);
            }
        });
        jPanel1.add(jTextField4);
        jTextField4.setBounds(580, 220, 360, 25);

        jScrollPane4.setFont(new java.awt.Font("Baskerville Old Face", 1, 14)); // NOI18N

        jTable4.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Cod. Producto", "Nombre ", "Descripcion", "Marca", "Existencias"
            }
        ));
        jTable4.setEnabled(false);
        jScrollPane4.setViewportView(jTable4);

        jPanel1.add(jScrollPane4);
        jScrollPane4.setBounds(580, 250, 614, 205);

        jButton1.setFont(new java.awt.Font("Baskerville Old Face", 1, 14)); // NOI18N
        jButton1.setText("<<");
        jButton1.setEnabled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(510, 310, 55, 65);

        jButton3.setText("Realizar Venta");
        jButton3.setEnabled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(146, 602, 169, 77);

        jLabel25.setFont(new java.awt.Font("Baskerville Old Face", 1, 24)); // NOI18N
        jLabel25.setText("Cambio:");
        jPanel1.add(jLabel25);
        jLabel25.setBounds(280, 220, 100, 24);

        jLabel26.setFont(new java.awt.Font("Baskerville Old Face", 1, 24)); // NOI18N
        jLabel26.setText("Q");
        jPanel1.add(jLabel26);
        jLabel26.setBounds(400, 220, 30, 24);

        jLabel27.setFont(new java.awt.Font("Baskerville Old Face", 1, 24)); // NOI18N
        jLabel27.setText("0.00");
        jPanel1.add(jLabel27);
        jLabel27.setBounds(440, 220, 50, 24);

        jLabel28.setFont(new java.awt.Font("Baskerville Old Face", 1, 24)); // NOI18N
        jLabel28.setText("No. Venta:");
        jPanel1.add(jLabel28);
        jLabel28.setBounds(1043, 16, 114, 24);

        jLabel29.setFont(new java.awt.Font("Baskerville Old Face", 1, 24)); // NOI18N
        jLabel29.setText("0");
        jPanel1.add(jLabel29);
        jLabel29.setBounds(1081, 59, 13, 24);

        jTabbedPane1.addTab("Venta", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 10, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 523, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 13, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField4KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField4KeyReleased
        Connection cn=null;
        PreparedStatement pst;
        ResultSet rs;
        String comodin= jTextField4.getText() + "%";
        //String sql= "SELECT CodProducto, NombreProducto,PrecioUProducto,PrecioMayoristaProducto,tblMarca_idtblMarca(SELECT NombreMarca FROM tblMarca WHERE idtblMarca=tblMarca_idtblMarca) FROM tblProductos WHERE NombreProducto like'"+comodin+"'";
       // String sql= "(SELECT CodProducto,NombreProducto,DescripcionProducto, PrecioUproducto, PrecioMProducto,Existencias,(SELECT NombreMarca FROM tblMarca WHERE idtblMarca=tblMarca_idtblMarca) FROM tblProductos WHERE NombreProducto like'"+comodin+"')";
        String sql= "(SELECT tblProductos.CodProducto,tblProductos.NombreProducto,tblProductos.DescripcionProducto,tblProductos.PrecioUproducto,tblProductos.PrecioMProducto, tblProductos  .Existencias, tblMarca.NombreMarca FROM tblProductos INNER JOIN tblMarca ON tblProductos.tblMarca_idtblMarca= tblMarca.idtblMarca WHERE NombreProducto like'"+comodin+"')";
        try {
            cn= conexion.getConexion();
            pst=cn.prepareCall(sql);
            rs=pst.executeQuery();
            jTable4.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jTextField4KeyReleased

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField4InputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_jTextField4InputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4InputMethodTextChanged

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
        if(jRadioButton2.isSelected()){
            jRadioButton1.setSelected(false);
            jTextField2.setEnabled(false);
            jButton2.setEnabled(false);
        }
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
        if(jRadioButton1.isSelected()){
            jTextField2.setEnabled(true);
            jButton2.setEnabled(true);
            jRadioButton2.setSelected(false);
        }else{
            jTextField2.setEnabled(false);
            jButton2.setEnabled(false);
        }
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioButton1ItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ItemStateChanged

    private void jTable1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTable1FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1FocusLost

    private void jTable1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTable1FocusGained
        // TODO add your handling code here:
        float total;
    }//GEN-LAST:event_jTable1FocusGained

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

        TransaccionVentas consulta= new TransaccionVentas();
        cliente inf= new cliente();
        try {
            if(consulta.GetInfoCliente(jTextField2.getText()).GetNombreCliente()==null){
                JOptionPane.showMessageDialog(rootPane, "No se encuentra el cliente, Necesita crear un cliente para poder continuar");
            }else{
                HabilitarVenta();
                try {
            inf=consulta.GetInfoCliente(jTextField2.getText());
            jLabel15.setText(inf.GetNombreCliente());
            jLabel16.setText(inf.GetApellidoCliente());
            jLabel20.setText(inf.GetTelefonoCliente());
            jLabel21.setText(inf.GetDireccionCliente());

                } catch (SQLException ex) {
                 Logger.getLogger(Venta.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ClassNotFoundException ex) {
                 Logger.getLogger(Venta.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(Venta.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Venta.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed
    public void HabilitarVenta(){
        jTextField4.setEnabled(true);
        jTable4.setEnabled(true);
        jButton1.setEnabled(true);
        jTable1.setEnabled(true);
        jButton3.setEnabled(true);
    }
    public void numeroVenta() throws ClassNotFoundException{
        TransaccionVentas obt= new TransaccionVentas();
        jLabel29.setText(String.valueOf(obt.ObtenerNumerVenta()));
    }
    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed
    DefaultTableModel m;
    int cont=0;
    float total; 
   
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         String Precio,Cantidad = null;
        if(jTable4.getSelectedRow()!=-1){
            String codigo, Nombre, PrecioU,PrecioM,CantidadS,Existencias;
            float subtotal;
            
             Precio=JOptionPane.showInputDialog("Que tipo de Precio Desea Utilizar U/M");
             if(Precio!=null && (Precio.equals("U")||Precio.equals("u")||Precio.equals("M")||Precio.equals("m"))){
                 Cantidad= JOptionPane.showInputDialog("Ingrese la cantidad de productos a vender");
                 try {
                      if(Cantidad==null){
                     JOptionPane.showMessageDialog(rootPane, "Se ha cancelado la agregacion del producto");
                 }else{
                     Existencias= jTable4.getValueAt(jTable4.getSelectedRow(), 5).toString();
                     if(Integer.valueOf(Existencias)<=0 ||Integer.valueOf(Cantidad)>Integer.valueOf(Existencias)){
                         JOptionPane.showMessageDialog(rootPane, "No se puede realizar esta venta");
                     }else{
                         
                         DefaultTableModel modelo= (DefaultTableModel) jTable1.getModel();
                         codigo=(String) jTable4.getValueAt(jTable4.getSelectedRow(), 0);
                         Nombre= jTable4.getValueAt(jTable4.getSelectedRow(), 1).toString();
                         PrecioU=jTable4.getValueAt(jTable4.getSelectedRow(), 3).toString();
                         PrecioM=jTable4.getValueAt(jTable4.getSelectedRow(), 4).toString();
                         
                         m=(DefaultTableModel) jTable1.getModel();
                         m.setNumRows(cont);
                         if(Precio.equals("M")|| Precio.equals("m")){
                             subtotal= Float.parseFloat(PrecioM) * Integer.parseInt(Cantidad);
                             cont++;
                             String elementos[]= {codigo,Nombre,PrecioM,Cantidad,String.valueOf(subtotal)};
                             m.addRow(elementos);
                             total+=subtotal;
                         }else{
                             if(Precio.equals("U")||Precio.equals("u")){
                                 subtotal= Float.parseFloat(PrecioU) * Integer.parseInt(Cantidad);
                               //  subtotal= Float.parseFloat(PrecioM) * Float.parseFloat(Cantidad);
                                 cont++;
                                 String elementos[]= {codigo,Nombre,PrecioU,Cantidad,String.valueOf(subtotal)};
                                 m.addRow(elementos);
                                 total+=subtotal;
                             }else{
                                 JOptionPane.showMessageDialog(rootPane, "Debio ingresar el tipo de precio a vender");
                             }
                         }
                         
                         jLabel23.setText(String.valueOf(total));
                         
                     }
                 }
                      } catch (NumberFormatException e) {
                          JOptionPane.showMessageDialog(rootPane, "el numero que ingreso no es un numero");
                 }
                
             }else{
                 JOptionPane.showMessageDialog(rootPane, "Se ha cancelado la agregacion del producto");
             }
             
            
             
           }   
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField3KeyReleased
        // TODO add your handling code here:
        if(jRadioButton6.isSelected()){
            
            ConsultaProductosNombre();
            
        }else{
            if(jRadioButton7.isSelected()){
             
                ConsultaProductosDescripcion();
            }else{
                if(jRadioButton8.isSelected()){
                   
                    ConsultaProductoCodigo();
                }
            }
        }
    }//GEN-LAST:event_jTextField3KeyReleased

    private void jRadioButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton6ActionPerformed
        // TODO add your handling code here:
        jRadioButton7.setSelected(false);
        jRadioButton8.setSelected(false);
    }//GEN-LAST:event_jRadioButton6ActionPerformed

    private void jRadioButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton7ActionPerformed
        // TODO add your handling code here:
        jRadioButton6.setSelected(false);
        jRadioButton8.setSelected(false);
    }//GEN-LAST:event_jRadioButton7ActionPerformed

    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased
        // TODO add your handling code here:
        if(jRadioButton3.isSelected()){
            ConsultaProductosNombre();
        }else{
            if(jRadioButton4.isSelected()){
                ConsultarClienteApellido();
            }else{
                if(jRadioButton5.isSelected()){
                    consultarClienteCodigo();
                }
            }
        }
    }//GEN-LAST:event_jTextField1KeyReleased

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        // TODO add your handling code here:
        jRadioButton4.setSelected(false);
        jRadioButton5.setSelected(false);
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed
        // TODO add your handling code here:
        jRadioButton3.setSelected(false);
        jRadioButton5.setSelected(false);
    }//GEN-LAST:event_jRadioButton4ActionPerformed

    private void jRadioButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton5ActionPerformed
        // TODO add your handling code here:
        jRadioButton4.setSelected(false);
        jRadioButton3.setSelected(false);
    }//GEN-LAST:event_jRadioButton5ActionPerformed
    int numeroFactura;
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String Pago;
        
        if(jTable1.getRowCount()==0 ||cont==0){
            JOptionPane.showMessageDialog(rootPane, "Nocesita agregar productos para poder efectuar la venta");
        }else{
              Pago= JOptionPane.showInputDialog("Ingrese El Pago");
             if(Float.parseFloat(Pago)==0 ||Float.parseFloat(Pago)<0||Float.parseFloat(Pago)<total){
                 JOptionPane.showMessageDialog(rootPane, "Pago Invalido");
             }else{
                 float cambio= Float.parseFloat(Pago)-total;
                  TransaccionVentas ventas= new TransaccionVentas();
                  jLabel27.setText(Float.toString(cambio));
                  try {
                       ventas.InsertarFactura(jTextField2.getText(), total, ObtenerFechaSistema(), Float.parseFloat(Pago), cambio, true);
                       numeroFactura=ventas.ObtenerNumeroFactura();
                       ventas.InsertarDetalleFactura(jTable1, numeroFactura);
                       JOptionPane.showMessageDialog(rootPane, "Venta Realizada Exitosamente");
                       RecorrerDetalleVenta();
                       refresh();
                   } catch (SQLException ex) {
                       JOptionPane.showMessageDialog(rootPane, ex);
                      Logger.getLogger(Venta.class.getName()).log(Level.SEVERE, null, ex);
                   } catch (ClassNotFoundException ex) {
                      Logger.getLogger(Venta.class.getName()).log(Level.SEVERE, null, ex);
                  }
             }
            
        }
        
    }//GEN-LAST:event_jButton3ActionPerformed
   
    public void GenerarReporte() throws JRException{
           
        try {
            com.mysql.jdbc.Connection cn= null;
            cn=(com.mysql.jdbc.Connection) conexion.getConexion();
            JasperReport jr =null;
            String archivo="/Users/DEOCCIDENTE/Downloads/puntovengaguadalupe/src/Reportes/reportventa.jasper"; 
            Map parametro= new HashMap();
            TransaccionVentas NoFact= new TransaccionVentas();
            parametro.put("idFactura", NoFact.ObtenerNumeroFactura());
            jr= (JasperReport) JRLoader.loadObjectFromFile(archivo);
            JasperPrint jp= JasperFillManager.fillReport(jr, parametro, cn);
            JasperViewer jv= new JasperViewer(jp,false);
            jv.setVisible(true);
            jv.setDefaultCloseOperation(javax.swing.JFrame.DISPOSE_ON_CLOSE);
            jv.setTitle("Reporte");
        } catch (SQLException ex) {
            Logger.getLogger(Venta.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Venta.class.getName()).log(Level.SEVERE, null, ex);
        }
           
               
            
    }
    public void RecorrerDetalleVenta() {
        List DetalleVenta= new ArrayList();
        camposDB tipo;
        DetalleVenta.clear();
        for(int i=0;i< jTable1.getRowCount();i++){
            tipo= new camposDB(jTable1.getValueAt(i, 0).toString(), (String) jTable1.getValueAt(i, 1), Float.valueOf((String) jTable1.getValueAt(i, 2)), Integer.parseInt((String) jTable1.getValueAt(i, 3)), Float.parseFloat((String) jTable1.getValueAt(i, 4)));
            DetalleVenta.add(tipo);
        }
        try {
            GenerarReporte();
        } catch (JRException ex) {
            Logger.getLogger(Venta.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    
    public void refresh(){
       total=0;
       numeroFactura=0;
       jLabel15.setText("");
       jLabel16.setText("");
       jLabel20.setText("");
       jLabel21.setText("");
       jTextField2.setText("");
       jRadioButton1.setSelected(false);
       jRadioButton2.setSelected(false);
       jLabel27.setText("0.00");
       jLabel23.setText("0.00");
       jTextField4.setText("");
      
       
    }
    public String ObtenerFechaSistema(){
        String fech;
            //en fecha obtenemos la fecha y hora del sistema
        Calendar fecha = new GregorianCalendar();
        //Obtenemos el valor del año, mes, día,
        //hora, minuto y segundo del sistema
        //usando el método get y el parámetro correspondiente
        int año = fecha.get(Calendar.YEAR);
        int mes = fecha.get(Calendar.MONTH);
        int dia = fecha.get(Calendar.DAY_OF_MONTH);
        fech= año +"."+mes+"."+dia;
        
        return fech;
    }
    public void ConsultarClienteNombre(){
         Connection cn=null;
        PreparedStatement pst;
        ResultSet rs;
        String comodin= jTextField1.getText() + "%";
        //String sql= "SELECT CodProducto, NombreProducto,PrecioUProducto,PrecioMayoristaProducto,tblMarca_idtblMarca(SELECT NombreMarca FROM tblMarca WHERE idtblMarca=tblMarca_idtblMarca) FROM tblProductos WHERE NombreProducto like'"+comodin+"'";
        String sql= "(SELECT CodCliente,NombreCliente,ApellidoCliente, TelefonoCliente, DireccionCliente FROM tblClientes WHERE NombreCliente like '"+comodin+"')";
       
        try {
            cn= conexion.getConexion();
            pst=cn.prepareCall(sql);
            rs=pst.executeQuery();
            jTable2.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception e) {
        }
    }
    public void ConsultarClienteApellido(){
         Connection cn=null;
        PreparedStatement pst;
        ResultSet rs;
        String comodin= jTextField1.getText() + "%";
        //String sql= "SELECT CodProducto, NombreProducto,PrecioUProducto,PrecioMayoristaProducto,tblMarca_idtblMarca(SELECT NombreMarca FROM tblMarca WHERE idtblMarca=tblMarca_idtblMarca) FROM tblProductos WHERE NombreProducto like'"+comodin+"'";
        String sql= "(SELECT CodCliente,NombreCliente,ApellidoCliente, TelefonoCliente, DireccionCliente FROM tblClientes WHERE ApellidoCliente like '"+comodin+"')";
       
        try {
            cn= conexion.getConexion();
            pst=cn.prepareCall(sql);
            rs=pst.executeQuery();
            jTable2.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception e) {
        }
    }
    public void consultarClienteCodigo(){
         Connection cn=null;
        PreparedStatement pst;
        ResultSet rs;
        String comodin= jTextField1.getText() + "%";
        //String sql= "SELECT CodProducto, NombreProducto,PrecioUProducto,PrecioMayoristaProducto,tblMarca_idtblMarca(SELECT NombreMarca FROM tblMarca WHERE idtblMarca=tblMarca_idtblMarca) FROM tblProductos WHERE NombreProducto like'"+comodin+"'";
        String sql= "(SELECT CodCliente,NombreCliente,ApellidoCliente, TelefonoCliente, DireccionCliente FROM tblClientes WHERE CodCliente like '"+comodin+"')";
       
        try {
            cn= conexion.getConexion();
            pst=cn.prepareCall(sql);
            rs=pst.executeQuery();
            jTable2.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception e) {
        }
    }
    public void ConsultaProductosNombre(){
         Connection cn=null;
        PreparedStatement pst;
        ResultSet rs;
        String comodin= jTextField3.getText() + "%";
        //String sql= "SELECT CodProducto, NombreProducto,PrecioUProducto,PrecioMayoristaProducto,tblMarca_idtblMarca(SELECT NombreMarca FROM tblMarca WHERE idtblMarca=tblMarca_idtblMarca) FROM tblProductos WHERE NombreProducto like'"+comodin+"'";
        //String sql= "(SELECT CodProducto,NombreProducto,DescripcionProducto, PrecioUproducto, PrecioMProducto,Existencias,(SELECT NombreMarca FROM tblMarca WHERE idtblMarca=tblMarca_idtblMarca) FROM tblProductos WHERE NombreProducto like '"+comodin+"')";
       String sql= "(SELECT tblProductos.CodProducto,tblProductos.NombreProducto,tblProductos.DescripcionProducto,tblProductos.PrecioUproducto,tblProductos.PrecioMProducto, tblMarca.NombreMarca FROM tblProductos INNER JOIN tblMarca ON tblProductos.tblMarca_idtblMarca= tblMarca.idtblMarca WHERE NombreProducto like'"+comodin+"')";
        try {
            cn= conexion.getConexion();
            pst=cn.prepareCall(sql);
            rs=pst.executeQuery();
            jTable3.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception e) {
        }
    }
    public void ConsultaProductosDescripcion(){
         Connection cn=null;
        PreparedStatement pst;
        ResultSet rs;
        String comodin= jTextField3.getText() + "%";
        //String sql= "SELECT CodProducto, NombreProducto,PrecioUProducto,PrecioMayoristaProducto,tblMarca_idtblMarca(SELECT NombreMarca FROM tblMarca WHERE idtblMarca=tblMarca_idtblMarca) FROM tblProductos WHERE NombreProducto like'"+comodin+"'";
        // String sql= "(SELECT CodProducto,NombreProducto,DescripcionProducto, PrecioUproducto, PrecioMProducto,Existencias,(SELECT NombreMarca FROM tblMarca WHERE idtblMarca=tblMarca_idtblMarca) FROM tblProductos WHERE DescripcionProducto like'"+comodin+"')";
       String sql= "(SELECT tblProductos.CodProducto,tblProductos.NombreProducto,tblProductos.DescripcionProducto,tblProductos.PrecioUproducto,tblProductos.PrecioMProducto, tblMarca.NombreMarca FROM tblProductos INNER JOIN tblMarca ON tblProductos.tblMarca_idtblMarca= tblMarca.idtblMarca WHERE DescripcionProducto like'"+comodin+"')";
        try {
            cn= conexion.getConexion();
            pst=cn.prepareCall(sql);
            rs=pst.executeQuery();
            jTable3.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception e) {
        }
    }
    public void ConsultaProductoCodigo(){
         Connection cn=null;
        PreparedStatement pst;
        ResultSet rs;
        String comodin= jTextField3.getText() + "%";
        //String sql= "SELECT CodProducto, NombreProducto,PrecioUProducto,PrecioMayoristaProducto,tblMarca_idtblMarca(SELECT NombreMarca FROM tblMarca WHERE idtblMarca=tblMarca_idtblMarca) FROM tblProductos WHERE NombreProducto like'"+comodin+"'";
       // String sql= "(SELECT CodProducto,NombreProducto,DescripcionProducto, PrecioUproducto, PrecioMProducto,Existencias,(SELECT NombreMarca FROM tblMarca WHERE idtblMarca=tblMarca_idtblMarca) FROM tblProductos WHERE CodProducto like'"+comodin+"')";
        String sql= "(SELECT tblProductos.CodProducto,tblProductos.NombreProducto,tblProductos.DescripcionProducto,tblProductos.PrecioUproducto,tblProductos.PrecioMProducto, tblMarca.NombreMarca FROM tblProductos INNER JOIN tblMarca ON tblProductos.tblMarca_idtblMarca= tblMarca.idtblMarca WHERE CodProducto like'"+comodin+"')";
       
        try {
            cn= conexion.getConexion();
            pst=cn.prepareCall(sql);
            rs=pst.executeQuery();
            jTable3.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception e) {
        }
    }
    
    public void buscarNombreProducto(String CodProducto) throws SQLException, ClassNotFoundException{
        producto produ= new producto();
        Connection con= null;
        con=conexion.getConexion();
        Statement st = con.createStatement();
        ResultSet rs = st.executeQuery("SELECT CodProducto, NombreProducto, PrecioUProducto, PrecioMProducto,Existencias,DescripcionProducto FROM tblProductos WHERE CodProducto like '%" +CodProducto+'%');
        ResultSetMetaData rsMd = (ResultSetMetaData) rs.getMetaData();
         st = (Statement) con.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
        produ.SetNombreProducto(rs.getString("NombreProducto").intern());
        produ.SetPrecioUnitario(rs.getFloat("PrecioUProducto"));
        produ.SetPrecioMayorista(rs.getFloat("PrecioMProducto"));
        produ.SetExistencias(rs.getInt("Existencias"));
        produ.SetDescripcion(rs.getString("DescripcionProducto"));
        
        st.close();
        con.close();
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Venta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Venta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Venta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Venta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Venta().setVisible(true);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(Venta.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JRadioButton jRadioButton8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
}
